language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"
env: RAPILA_ENVIRONMENT=test PHPUNIT_PATH=phpunit MIGRATION_SUDO=env SKIP_ICONV_TESTS=1
sudo: false
before_install:
    - mkdir .base
    - mv * .git* .travis.yml .base/
    - mv .base base
    - git init
    - git remote add origin git://github.com/rapila/cms-full.git
    - git checkout -b tmp && git branch -D master
    - git fetch ---all
    - git checkout "$TRAVIS_BRANCH" || git checkout master
    - ./base/scripts/create-folders.sh
    - ./base/scripts/generate-model.sh
script: ./base/scripts/run-tests.sh
addons:
  apt:
    packages:
    - locales
    - language-pack-de
    - language-pack-uk
    - language-pack-en



REV="$(git describe --all --contains || echo 'master')"
REV="${REV#remotes/origin/}"
REV="${REV#tags/}"
REV="${REV%~*}"
