modules:
  _default: file
  # Set images cache explicitly so that overriding the default will still store these large files on the file system
  images: file

strategies:
  # This strategy should not be removed. It can be reconfigured but some internals rely on it being there.
  file:
    class: CachingStrategyFile
    options:
      file_name: "generated/caches/${module}/${key}.cache"
      key_encode: "md5"
  off:
    class: CachingStrategyNone

# Options set here apply to all strategies (unless overridden)
options:
  # Experimental: set this to true if you have an opcode cache
  use_var_export: false
