modules:
  _default: file
  # Set images cache explicitly so that overriding the default will still store these large files on the file system
  images: file
  navigation: 'off'

strategies:
  # This strategy should not be removed. It can be reconfigured but some internals rely on it being there.
  file:
    class: CachingStrategyFile
    options:
      file_name: "generated/caches/${module}/${key}.cache"
      key_encode: "md5"
  off:
    class: CachingStrategyNone
    options:
      # Uncached resources should expire immediately
      expires: false

# Options set here apply to all strategies (unless overridden)
options:
  # Experimental: set this to true if you have an opcode cache
  use_var_export: false
  # those don’t work well in some environments but should usually be fine. Turning off these also turns off 304 Not Modified responses
  send_not_modified_response: true
  # default ttl for cached responses. Possible values are documented in LinkUtil::sendExpires
  expires:
    # Do not send an Expires header by default
    _default: null
    # Versioned resource can live inefinitely
    versioned: true
