admin_menu:
  left:
    - preview
    - edit
    -
      - module.documents
      - module.links
      - ~
      - module.users
    - module.dashboard
  right:
    - activity
    - logo
    - documentation
    - tag
    -
      - type.menu # Configure the kind of menu
      - icon.action # The menu’s icon
      - user
      - clear_caches
      - reset_user_settings
    - logout

rich_text:
  buttons: [['bold', 'italic', '~'], []]

dashboard:
  layout: 2cols2thirds
  widgets:
    -
      type: static_text
      title: "Welcome"
      color: '#8dc100'
      contrastColor: 'black'
      container: 'column-1'
      config:
        text: '<h3>Introduction to your Dashboard</h3><p>The Dashboard allows you to see all the information that is most relevant to you.</p><p>You can organize the widgets as you like. Dashboard widgets can be added using the “+” Icon at the bottom-left or using the access key “n”: just choose a type and container and you’re good to go.</p><p>To change the Dashboard layout, use the dropdown on the bottom. Each layout contains containers into which your widgets can be easily organized simply by dragging them.</p><p>To edit a widget, click the edit button in its title bar; to remove it, click the “╳” icon.</p>'
    -
      type: recent_activity
      title: "Activity in Pages"
      color: "#554499"
      contrastColor: white
      container: 'column-2'
      config:
        days: 3
        models: ['Page']
    -
      type: recent_activity
      title:  "Activity in Documents"
      color: "#99794B"
      contrastColor: white
      container: 'column-2'
      config:
        days: 10
        models: ['Document']
    -
      type: recent_activity
      title: "Activity in Links"
      color: "#316E99"
      contrastColor: white
      container: 'column-2'
      config:
        days: 10
        models: ['Link']
